# -*- coding: utf-8 -*-
"""ImageClassification_Submission.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CyLKumMeiqCP2tCRMVXmSPA3F5Ufdz3_

## Image Classification Submission


> Dataset diperoleh dari [kaggle](https://www.kaggle.com/datasets/vencerlanz09/bottle-synthetic-images-dataset)

> Dataset berisi 5 kelas data klasifikasi botol


> Jumlah dataset 25000 gambar dengan resolusi yang berbeda-beda

### Import Library
"""

import importlib.util
import subprocess
import sys

required_packages = [
    "kagglehub",
    "tensorflow",
    "numpy",
    "opencv-python",
    "pandas",
    "matplotlib",
    "seaborn",
]

missing_packages = [pkg for pkg in required_packages if importlib.util.find_spec(pkg.split("-")[0]) is None]
if missing_packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", *missing_packages])

import kagglehub
import os
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import cv2
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

"""### Prepare Data from Kaggle API"""

try:
    path = kagglehub.dataset_download("vencerlanz09/bottle-synthetic-images-dataset")
    print("Path to dataset files:", path)
except Exception as err:
    raise RuntimeError(
        "Download gagal. Pastikan koneksi internet aktif, lalu jalankan ulang script."
    ) from err

data = os.path.join(path, "Bottle Images", "Bottle Images")

"""### Kelas data pada Dataset"""

class_names = os.listdir(data)
class_names

"""### Sample Image Data dengan Resolusi yang berbeda-beda"""

img = cv2.imread(os.path.join(data, 'Beer Bottles', '00000000.jpg'))
plt.imshow(img)
plt.show()

img = cv2.imread(os.path.join(data, 'Soda Bottle', '00000000.jpg'))
plt.imshow(img)
plt.show()

"""### Resize seluruh gambar ke ukuran 150x10 untuk increase Training Time"""

import PIL
import os.path
from PIL import Image

f = os.path.join(data, 'Wine Bottle')
for file in os.listdir(f):
    f_img = os.path.join(f, file)
    img = Image.open(f_img)
    img = img.resize((150,150))
    img.save(f_img)

"""### Augmentasi Data"""

train_generator = ImageDataGenerator(
    shear_range=0.2,
    zoom_range=0.2,
    fill_mode='nearest',
    horizontal_flip=True,
    rescale=1./255,
    validation_split=0.2
)

test_generator = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

data_train = train_generator.flow_from_directory (
    data,
    target_size=(150,150),
    color_mode='rgb',
    class_mode='categorical',
    batch_size=32,
    subset='training'
)

data_test = test_generator.flow_from_directory (
    data,
    target_size=(150,150),
    color_mode='rgb',
    class_mode='categorical',
    batch_size=32,
    subset='validation'
)

"""### Define Learning Rate"""

optimizer = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0)

"""### Arsitektur Model"""

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same', input_shape=(150,150,3)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax'),
])
model.compile(loss = "categorical_crossentropy", optimizer = optimizer , metrics = ["accuracy"])

"""### Define Callbacks"""

# Callback agar model berhenti menjalankan proses training saat mencapai nilai akurasi 99%
class MyCallback (tf.keras.callbacks.Callback):
    def on_epoch_end (self, epoch, logs={}):
        if(logs.get('accuracy')>0.99):
            print("\nAkurasi telah mencapai 99% membatalkan proses training")
            self.model.stop_training = True

callbacks = MyCallback()

"""### Define Early Stop Training per 10 epochs """

checkpoint = tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)

history = model.fit(
    data_train,
    steps_per_epoch= 20000 // 32,
    epochs= 32,
    validation_data=data_test,
    validation_steps= 5000 // 32, 
    callbacks=[checkpoint, callbacks]
)

"""### Model Summary"""

model.summary()

"""### Plot Loss dan Akurasi"""

fig, axarr = plt.subplots(1,2, figsize=(15,5), sharex=True)

sns.set(style="ticks", font_scale = 1)
sns.despine(top=True, right=True, left=False, bottom=False)

historyDF = pd.DataFrame.from_dict(history.history)
ax = sns.lineplot(x = historyDF.index, y = history.history['accuracy'], ax=axarr[0], label="Training");
ax = sns.lineplot(x = historyDF.index, y = history.history['val_accuracy'], ax=axarr[0], label="Validation");
ax.set_ylabel('Accuracy')

ax = sns.lineplot(x = historyDF.index, y = history.history['loss'], ax=axarr[1], label="Training");
ax = sns.lineplot(x = historyDF.index, y = history.history['val_loss'], ax=axarr[1], label="Validation");
ax.set_ylabel('Loss')


axarr[0].set_title('Accuracy')
axarr[1].set_title('Loss')

for ax in axarr:
    ax.set_xlabel('Epochs')

plt.suptitle('Training and Performance Model', fontsize=16, weight='bold');
fig.tight_layout(pad=3.0)
plt.show()

"""### Save Model"""

dir = 'saved_model/'
tf.saved_model.save(model, dir)

"""### Convert Model to TFLite"""

converter = tf.lite.TFLiteConverter.from_saved_model(dir)
tflite_model = converter.convert()
 
with tf.io.gfile.GFile('model_tflite_version.tflite', 'wb') as f:
    f.write(tflite_model)